### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by weiyuxingchen** [facebookincubator/mvfst#74]
using:
Ubuntu 16.04
cmake 3.10
gcc 5.4
boost 1.62

running build_helper.sh, it seems all of the dependencies have built correctly, but when it gets to the end and tries to build mvfst itself, I get the following compiler error:

make -j 4
[ 1%] Built target mvfst_bufutil
[ 1%] Performing update step for 'googletest'
[ 2%] Built target mvfst_exception
[ 2%] Built target mvfst_constants
[ 2%] Performing configure step for 'googletest'
[ 3%] Built target mvfst_looper
loading initial cache file /home/h3c/ywc/mvfst/_build/build/googletest/tmp/googletest-cache-RelWithDebInfo.cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/h3c/ywc/mvfst/_build/build/googletest/src/googletest-build
[ 6%] Built target mvfst_codec_types
[ 6%] Performing build step for 'googletest'
[ 27%] Built target gmock
[ 7%] Built target mvfst_codec_decode
[ 45%] Built target gtest
[ 81%] Built target gmock_main
[100%] Built target gtest_main
[ 7%] No install step for 'googletest'
[ 7%] Built target mvfst_codec_packet_number_cipher
[ 8%] Completed 'googletest'
[ 10%] Built target googletest
[ 11%] Built target QuicConnectionIdTest
[ 12%] Built target PacketNumberTest
[ 12%] Linking CXX executable QuicIntegerTest
[ 15%] Built target mvfst_handshake
[ 16%] Built target mvfst_codec_pktbuilder
[ 16%] Linking CXX executable FizzPacketNumberCipherTest
[ 18%] Built target mvfst_codec
[ 18%] Building CXX object quic/state/CMakeFiles/mvfst_state_machine.dir/StateData.cpp.o
CMakeFiles/QuicIntegerTest.dir/QuicIntegerTest.cpp.o：在函数‘quic::test::QuicIntegerEncodeTest_Encode_Test::TestBody()’中：
/home/h3c/ywc/mvfst/quic/codec/test/QuicIntegerTest.cpp:77：对‘quic::BufAppender::BufAppender(folly::IOBuf*, unsigned long)’未定义的引用
../libmvfst_codec_types.a(QuicInteger.cpp.o)：在函数‘void quic::BufAppender::writeBE(unsigned long)’中：
/home/h3c/ywc/mvfst/quic/common/BufUtil.h:74：对‘quic::BufAppender::push(unsigned char const*, unsigned long)’未定义的引用
../libmvfst_codec_types.a(QuicInteger.cpp.o)：在函数‘void quic::BufAppender::writeBE(unsigned char)’中：
/home/h3c/ywc/mvfst/quic/common/BufUtil.h:74：对‘quic::BufAppender::push(unsigned char const*, unsigned long)’未定义的引用
../libmvfst_codec_types.a(QuicInteger.cpp.o)：在函数‘void quic::BufAppender::writeBE(unsigned int)’中：
/home/h3c/ywc/mvfst/quic/common/BufUtil.h:74：对‘quic::BufAppender::push(unsigned char const*, unsigned long)’未定义的引用
../libmvfst_codec_types.a(QuicInteger.cpp.o)：在函数‘void quic::BufAppender::writeBE(unsigned short)’中：
/home/h3c/ywc/mvfst/quic/common/BufUtil.h:74：对‘quic::BufAppender::push(unsigned char const*, unsigned long)’未定义的引用
collect2: error: ld returned 1 exit status
quic/codec/test/CMakeFiles/QuicIntegerTest.dir/build.make:157: recipe for target 'quic/codec/test/QuicIntegerTest' failed
make[2]: *** [quic/codec/test/QuicIntegerTest] Error 1
CMakeFiles/Makefile2:2603: recipe for target 'quic/codec/test/CMakeFiles/QuicIntegerTest.dir/all' failed
make[1]: *** [quic/codec/test/CMakeFiles/QuicIntegerTest.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
../../codec/libmvfst_codec_types.a(QuicInteger.cpp.o)：在函数‘void quic::BufAppender::writeBE(unsigned long)’中：
/home/h3c/ywc/mvfst/quic/common/BufUtil.h:74：对‘quic::BufAppender::push(unsigned char const*, unsigned long)’未定义的引用
../../codec/libmvfst_codec_types.a(QuicInteger.cpp.o)：在函数‘void quic::BufAppender::writeBE(unsigned char)’中：
/home/h3c/ywc/mvfst/quic/common/BufUtil.h:74：对‘quic::BufAppender::push(unsigned char const*, unsigned long)’未定义的引用
../../codec/libmvfst_codec_types.a(QuicInteger.cpp.o)：在函数‘void quic::BufAppender::writeBE(unsigned int)’中：
/home/h3c/ywc/mvfst/quic/common/BufUtil.h:74：对‘quic::BufAppender::push(unsigned char const*, unsigned long)’未定义的引用
../../codec/libmvfst_codec_types.a(QuicInteger.cpp.o)：在函数‘void quic::BufAppender::writeBE(unsigned short)’中：
/home/h3c/ywc/mvfst/quic/common/BufUtil.h:74：对‘quic::BufAppender::push(unsigned char const*, unsigned long)’未定义的引用
collect2: error: ld returned 1 exit status
quic/handshake/test/CMakeFiles/FizzPacketNumberCipherTest.dir/build.make:160: recipe for target 'quic/handshake/test/FizzPacketNumberCipherTest' failed
make[2]: *** [quic/handshake/test/FizzPacketNumberCipherTest] Error 1
CMakeFiles/Makefile2:3406: recipe for target 'quic/handshake/test/CMakeFiles/FizzPacketNumberCipherTest.dir/all' failed
make[1]: *** [quic/handshake/test/CMakeFiles/FizzPacketNumberCipherTest.dir/all] Error 2
/home/h3c/ywc/mvfst/quic/state/StateData.cpp: In member function ‘bool quic::QuicConnectionStateBase::retireAndSwitchPeerConnectionIds()’:
/home/h3c/ywc/mvfst/quic/state/StateData.cpp:161:22: error: could not convert ‘((quic::QuicConnectionStateBase*)this)->quic::QuicConnectionStateBase::nodeType’ from ‘quic::QuicNodeType’ to ‘bool’
auto& mainPeerId = nodeType == QuicNodeType::Client ? serverConnectionId
^
quic/state/CMakeFiles/mvfst_state_machine.dir/build.make:110: recipe for target 'quic/state/CMakeFiles/mvfst_state_machine.dir/StateData.cpp.o' failed
make[2]: *** [quic/state/CMakeFiles/mvfst_state_machine.dir/StateData.cpp.o] Error 1
CMakeFiles/Makefile2:4467: recipe for target 'quic/state/CMakeFiles/mvfst_state_machine.dir/all' failed
make[1]: *** [quic/state/CMakeFiles/mvfst_state_machine.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yangchi** [comment]
thank you for reporting. I think it's caused by https://github.com/facebookincubator/mvfst/commit/7ad8cea407a3e3680e8f32f901c275098326e724. Looking

**Comment by yangchi** [comment]
This should be fixed after https://github.com/facebookincubator/mvfst/commit/6fd3a000d3113f75c1b67a29b3179a28475e6768. Please pull latest and build again. Feel free to reopen if you still see errors.

**Comment by weiyuxingchen** [comment]
Thanks for your reply.  Some questions no longer appear, but there are still the following questions:

+ make -j 4
[  1%] Performing update step for 'googletest'
[  2%] Built target mvfst_bufutil
[  3%] Built target mvfst_constants
[  3%] Performing configure step for 'googletest'
[  4%] Built target mvfst_exception
loading initial cache file /home/h3c/ywc/mvfst/_build/build/googletest/tmp/googletest-cache-RelWithDebInfo.cmake
[  5%] Built target mvfst_looper
-- Configuring done
[  7%] Built target mvfst_codec_types
-- Generating done
-- Build files have been written to: /home/h3c/ywc/mvfst/_build/build/googletest/src/googletest-build
[  8%] Performing build step for 'googletest'
[  9%] Built target mvfst_codec_decode
[ 36%] Built target gmock_main
[ 63%] Built target gmock
[ 81%] Built target gtest
[100%] Built target gtest_main
[ 10%] Built target mvfst_codec_packet_number_cipher
[ 10%] No install step for 'googletest'
[ 10%] Completed 'googletest'
[ 11%] Built target googletest
Scanning dependencies of target PacketNumberTest
Scanning dependencies of target QuicConnectionIdTest
Scanning dependencies of target QuicIntegerTest
[ 14%] Built target mvfst_handshake
[ 14%] Building CXX object quic/codec/test/CMakeFiles/QuicConnectionIdTest.dir/QuicConnectionIdTest.cpp.o
[ 15%] Built target mvfst_codec_pktbuilder
Scanning dependencies of target FizzPacketNumberCipherTest
[ 16%] Building CXX object quic/codec/test/CMakeFiles/QuicIntegerTest.dir/QuicIntegerTest.cpp.o
[ 16%] Building CXX object quic/codec/test/CMakeFiles/PacketNumberTest.dir/PacketNumberTest.cpp.o
[ 16%] Building CXX object quic/handshake/test/CMakeFiles/FizzPacketNumberCipherTest.dir/FizzPacketNumberCipherTest.cpp.o
[ 16%] Building CXX object quic/codec/test/CMakeFiles/QuicConnectionIdTest.dir/__/__/common/test/TestMain.cpp.o
[ 17%] Linking CXX executable QuicConnectionIdTest
[ 17%] Building CXX object quic/codec/test/CMakeFiles/QuicIntegerTest.dir/__/__/common/test/TestMain.cpp.o
[ 17%] Built target QuicConnectionIdTest
[ 18%] Building CXX object quic/handshake/test/CMakeFiles/FizzPacketNumberCipherTest.dir/__/__/common/test/TestMain.cpp.o
[ 19%] Building CXX object quic/codec/test/CMakeFiles/PacketNumberTest.dir/__/__/common/test/TestMain.cpp.o
[ 20%] Linking CXX executable QuicIntegerTest
[ 21%] Built target mvfst_codec
[ 21%] Building CXX object quic/state/CMakeFiles/mvfst_state_machine.dir/StateData.cpp.o
[ 21%] Linking CXX executable PacketNumberTest
[ 21%] Built target QuicIntegerTest
[ 22%] Building CXX object quic/state/CMakeFiles/mvfst_state_machine.dir/PendingPathRateLimiter.cpp.o
[ 22%] Linking CXX executable FizzPacketNumberCipherTest
[ 22%] Built target PacketNumberTest
[ 22%] Built target FizzPacketNumberCipherTest
/home/h3c/ywc/mvfst/quic/state/StateData.cpp: In member function ‘bool quic::QuicConnectionStateBase::retireAndSwitchPeerConnectionIds()’:
/home/h3c/ywc/mvfst/quic/state/StateData.cpp:161:22: error: could not convert ‘((quic::QuicConnectionStateBase*)this)->quic::QuicConnectionStateBase::nodeType’ from ‘quic::QuicNodeType’ to ‘bool’
   auto& mainPeerId = nodeType == QuicNodeType::Client ? serverConnectionId
                      ^
quic/state/CMakeFiles/mvfst_state_machine.dir/build.make:110: recipe for target 'quic/state/CMakeFiles/mvfst_state_machine.dir/StateData.cpp.o' failed
make[2]: *** [quic/state/CMakeFiles/mvfst_state_machine.dir/StateData.cpp.o] Error 1
CMakeFiles/Makefile2:4426: recipe for target 'quic/state/CMakeFiles/mvfst_state_machine.dir/all' failed
make[1]: *** [quic/state/CMakeFiles/mvfst_state_machine.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by weiyuxingchen** [comment]
Duplicate of #
