### ISSUE TITLE
Compilation is currently broken on master

### ISSUE THREAD

**Issue by odelalleau** [facebookincubator/mvfst#214]
There is a compilation error:
```
[ 17%] Building CXX object quic/fizz/handshake/CMakeFiles/mvfst_fizz_handshake.dir/FizzPacketNumberCipher.cpp.o
/private/home/odelalleau/src/mvfst/quic/fizz/handshake/QuicFizzFactory.cpp:54:20: error: ‘fizz::TLSContent {anonymous}::QuicPlaintextWriteRecordLayer::write(fizz::TLSMessage&&, fizz::Aead::AeadOptions) const’ marked ‘override’, but does not override
   54 |   fizz::TLSContent write(
      |                    ^~~~~
```

This seems to be caused by c84d57ba726ff25557a35093c6ed253dda58e22c -- I suspect that this commit depends on an update to fizz that hasn't been pushed out yet.

**Comment by lnicco** [comment]
apologies for the breakage. 
Commit sync to github was blocked for a while. 
this should be fixed now
